version: '3.8'

services:
  nginx:
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:8000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_PORT=27017
      - PORT=3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - WDS_SOCKET_PORT=80
      - REACT_APP_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/frontend

  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=appdb
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
